
package introsde.experienceadapter.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExperienceService", targetNamespace = "http://soap.experienceadapter.introsde/", wsdlLocation = "https://experienceadapter.herokuapp.com/?wsdl")
public class ExperienceService
    extends Service
{

    private final static URL EXPERIENCESERVICE_WSDL_LOCATION;
    private final static WebServiceException EXPERIENCESERVICE_EXCEPTION;
    private final static QName EXPERIENCESERVICE_QNAME = new QName("http://soap.experienceadapter.introsde/", "ExperienceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://experienceadapter.herokuapp.com/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXPERIENCESERVICE_WSDL_LOCATION = url;
        EXPERIENCESERVICE_EXCEPTION = e;
    }

    public ExperienceService() {
        super(__getWsdlLocation(), EXPERIENCESERVICE_QNAME);
    }

    public ExperienceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXPERIENCESERVICE_QNAME, features);
    }

    public ExperienceService(URL wsdlLocation) {
        super(wsdlLocation, EXPERIENCESERVICE_QNAME);
    }

    public ExperienceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXPERIENCESERVICE_QNAME, features);
    }

    public ExperienceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExperienceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExperienceAdapter
     */
    @WebEndpoint(name = "ExperienceAdapterImplPort")
    public ExperienceAdapter getExperienceAdapterImplPort() {
        return super.getPort(new QName("http://soap.experienceadapter.introsde/", "ExperienceAdapterImplPort"), ExperienceAdapter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExperienceAdapter
     */
    @WebEndpoint(name = "ExperienceAdapterImplPort")
    public ExperienceAdapter getExperienceAdapterImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.experienceadapter.introsde/", "ExperienceAdapterImplPort"), ExperienceAdapter.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXPERIENCESERVICE_EXCEPTION!= null) {
            throw EXPERIENCESERVICE_EXCEPTION;
        }
        return EXPERIENCESERVICE_WSDL_LOCATION;
    }

}
