
package introsde.experienceadapter.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExperienceAdapter", targetNamespace = "http://soap.experienceadapter.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExperienceAdapter {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns introsde.experienceadapter.soap.Experience
     */
    @WebMethod
    @WebResult(name = "getIndications", targetNamespace = "")
    @RequestWrapper(localName = "getIndications", targetNamespace = "http://soap.experienceadapter.introsde/", className = "introsde.experienceadapter.soap.GetIndications")
    @ResponseWrapper(localName = "getIndicationsResponse", targetNamespace = "http://soap.experienceadapter.introsde/", className = "introsde.experienceadapter.soap.GetIndicationsResponse")
    @Action(input = "http://soap.experienceadapter.introsde/ExperienceAdapter/getIndicationsRequest", output = "http://soap.experienceadapter.introsde/ExperienceAdapter/getIndicationsResponse")
    public Experience getIndications(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
