
package introsde.resourceadapter.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ResourceAdapterLogic", targetNamespace = "http://soap.resourceadapter.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ResourceAdapterLogic {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addArtist", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.AddArtist")
    @ResponseWrapper(localName = "addArtistResponse", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.AddArtistResponse")
    @Action(input = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/addArtistRequest", output = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/addArtistResponse")
    public void addArtist(
        @WebParam(name = "arg0", targetNamespace = "")
        Preference arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removeArtist", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.RemoveArtist")
    @ResponseWrapper(localName = "removeArtistResponse", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.RemoveArtistResponse")
    @Action(input = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/removeArtistRequest", output = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/removeArtistResponse")
    public void removeArtist(
        @WebParam(name = "arg0", targetNamespace = "")
        Preference arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<introsde.resourceadapter.soap.Artist>
     */
    @WebMethod
    @WebResult(name = "recommendedSimilarArtistList", targetNamespace = "")
    @RequestWrapper(localName = "getRecommendedSimilarArtists", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.GetRecommendedSimilarArtists")
    @ResponseWrapper(localName = "getRecommendedSimilarArtistsResponse", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.GetRecommendedSimilarArtistsResponse")
    @Action(input = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/getRecommendedSimilarArtistsRequest", output = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/getRecommendedSimilarArtistsResponse")
    public List<Artist> getRecommendedSimilarArtists(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<introsde.resourceadapter.soap.Event>
     */
    @WebMethod
    @WebResult(name = "recommendEventsList", targetNamespace = "")
    @RequestWrapper(localName = "recommendEvents", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.RecommendEvents")
    @ResponseWrapper(localName = "recommendEventsResponse", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.RecommendEventsResponse")
    @Action(input = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/recommendEventsRequest", output = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/recommendEventsResponse")
    public List<Event> recommendEvents(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getMotivation", targetNamespace = "")
    @RequestWrapper(localName = "getMotivation", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.GetMotivation")
    @ResponseWrapper(localName = "getMotivationResponse", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.GetMotivationResponse")
    @Action(input = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/getMotivationRequest", output = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/getMotivationResponse")
    public String getMotivation();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<introsde.resourceadapter.soap.Preference>
     */
    @WebMethod
    @WebResult(name = "getProfilePreferences", targetNamespace = "")
    @RequestWrapper(localName = "getProfilePreferences", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.GetProfilePreferences")
    @ResponseWrapper(localName = "getProfilePreferencesResponse", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.GetProfilePreferencesResponse")
    @Action(input = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/getProfilePreferencesRequest", output = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/getProfilePreferencesResponse")
    public List<Preference> getProfilePreferences(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(name = "getArtistExternalId", targetNamespace = "")
    @RequestWrapper(localName = "getArtistExternalId", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.GetArtistExternalId")
    @ResponseWrapper(localName = "getArtistExternalIdResponse", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.GetArtistExternalIdResponse")
    @Action(input = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/getArtistExternalIdRequest", output = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/getArtistExternalIdResponse")
    public Integer getArtistExternalId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getArtistNameFromExternalId", targetNamespace = "")
    @RequestWrapper(localName = "getArtistNameFromExternalId", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.GetArtistNameFromExternalId")
    @ResponseWrapper(localName = "getArtistNameFromExternalIdResponse", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.GetArtistNameFromExternalIdResponse")
    @Action(input = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/getArtistNameFromExternalIdRequest", output = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/getArtistNameFromExternalIdResponse")
    public String getArtistNameFromExternalId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "evaluateArtistRecommendation", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.EvaluateArtistRecommendation")
    @ResponseWrapper(localName = "evaluateArtistRecommendationResponse", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.EvaluateArtistRecommendationResponse")
    @Action(input = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/evaluateArtistRecommendationRequest", output = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/evaluateArtistRecommendationResponse")
    public void evaluateArtistRecommendation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Integer arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<introsde.resourceadapter.soap.Evaluation>
     */
    @WebMethod
    @WebResult(name = "getEvaluationsByUser", targetNamespace = "")
    @RequestWrapper(localName = "getEvaluationsByUser", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.GetEvaluationsByUser")
    @ResponseWrapper(localName = "getEvaluationsByUserResponse", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.GetEvaluationsByUserResponse")
    @Action(input = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/getEvaluationsByUserRequest", output = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/getEvaluationsByUserResponse")
    public List<Evaluation> getEvaluationsByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns introsde.resourceadapter.soap.Person
     */
    @WebMethod
    @WebResult(name = "getPersonByUser", targetNamespace = "")
    @RequestWrapper(localName = "getPersonByUser", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.GetPersonByUser")
    @ResponseWrapper(localName = "getPersonByUserResponse", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.GetPersonByUserResponse")
    @Action(input = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/getPersonByUserRequest", output = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/getPersonByUserResponse")
    public Person getPersonByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.resourceadapter.soap.Person>
     */
    @WebMethod
    @WebResult(name = "getAllUsers", targetNamespace = "")
    @RequestWrapper(localName = "getAllUsers", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.GetAllUsers")
    @ResponseWrapper(localName = "getAllUsersResponse", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.GetAllUsersResponse")
    @Action(input = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/getAllUsersRequest", output = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/getAllUsersResponse")
    public List<Person> getAllUsers();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "register", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://soap.resourceadapter.introsde/", className = "introsde.resourceadapter.soap.RegisterResponse")
    @Action(input = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/registerRequest", output = "http://soap.resourceadapter.introsde/ResourceAdapterLogic/registerResponse")
    public void register(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
